### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ayuhbelajar**

### CODE REVIEW

**Comment by supsa-ak** [comment]
Hi, can I contribute on this repository. I am participating in Hacktoberfest.

**Comment by jombelajar** [comment]
> Hi, can I contribute on this repository. I am participating in Hacktoberfest.

yeah,, sure. the purpose of this page is to show the landing page for promote private college programme.

**Comment by jombelajar** [comment]
> Hi, can I contribute on this repository. I am participating in Hacktoberfest.

you can also join this repo 

https://github.com/fare4z/ddt6b/tree/main/hacktoberfest 

just sharing what i found

**Comment by supsa-ak** [comment]
Can you suggest me something to work on. Like some feature or bug.

**Pull request merged**
